name: Test

on: [push, pull_request]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run:
        npm i
    - name: Test
      run:
        npm test